spring.application.name=spring-boot
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=pguser
spring.datasource.password=pgpassword
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
# Tells Hibernate to use the PostgreSQL 10 (or newer) engine but it will be selected by default
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver